### PR TITLE
cli login changes

### LINKED ISSUE #20: integrate commander client / config with nimbella cli credential store
- performed `client add` operation
- exited the repo then ran `nim commander` again which showed:
```
> nim commander
Your client: xyz (cli) (abc...)
Your namespace: not-my-slack-namespace
```

A csm install at that point failed with this message:
```
nc> csm_install .
  ✔ Packaging foo...
  ✔ Installing foo...
Error: You are not an administrator of nc application. Navigate to https://nimbella.com/resources-commander/reference#csm_install for more help.
```

### PR DESCRIPTION
**Pull request by niks3089**
Fixes #20

---
This change is [Reviewable](https://reviewable.io/reviews/nimbella/commander-cli/24)

### CODE REVIEW

File: src/commands/client/login.js [hunk 1]
```diff
@@ -17,6 +19,17 @@ module.exports = async args => {
     return error(`Failed to extract login creds from: ${token}`);
   }
 
+  const res = await invokeCommand('cli_login ' + token, token);
+  if (!res.data || !res.data.text) {
+    return error(`Failed to login using creds: ${token}`);
+  }
+  const cmd = shell.exec('nim auth login --auth ' + res.data.text);
```
Comment (rabbah) [inline src/commands/client/login.js:26]: why is a shell command needed in addition to the call to setCredentials (internal nim api) on line 21/34?

**Review by rabbah — APPROVED** [review]
I think this achieves the desired goal but I'm confused by the use a shell command in addition to the internal api.

File: src/commands/client/login.js (hunk 1 above)
Comment (niks3089) [reply src/commands/client/login.js:26]: Because it sets the `commander` specific creds under credentials.json and doesn't add the `namespace` creds.

Comment (rabbah) [reply src/commands/client/login.js:26]: There is a function in the credential store to do that:

https://github.com/nimbella/nimbella-cli/blob/b7979517229f514be664117ec287988a74ed3bf9/deployer/src/credentials.ts#L77
```
export function addCredential(store: CredentialStore, apihost: string, namespace: string, api_key: string, storage: string,
```

Comment (rabbah) [reply src/commands/client/login.js:26]: But i suppose you don't know the namespace thought at this point (although it can be fetched).

Comment (joshuaauerbachwatson) [reply src/commands/client/login.js:26]: I believe I understand how we may have gotten to this point.

It is not possible for commander-cli to use the command invocation API so, _if_ something needs to be done at that level you do have to spawn a process.   And, at one point, if you wanted to do a full login, you could not do that with the deployer API alone.

However, that has changed, so I think _now_ it should not be necessary to spawn.  You can use 

```
doLogin(token: string, persister: Persister, host: string = DEFAULT_API_HOST): Promise<Credentials>
```

The above function is exported by the deployer library.   It returns Credentials for convenience but it also stores them (it does the login).

Note that that _is_ a full login, using a token, but that's actually what you want because if you do a login using only `--auth` then you will not get full credentials.   So, the recommended flow (if all you have is an OW auth key) is (1) use the tokenizer API to convert that to a token, (2) use `doLogin` to fully login with that token (3) optionally add commander credentials with `addCommanderData` (you now know the namespace because it is in the returned Credentials).

Comment (rabbah) [reply src/commands/client/login.js:26]: Thanks for the clarification and explanation. We should adopt this approach. I am neutral on merging this pr and following it up with another. Will wait got Nikhil’s input. This patch is reviewed/approved.

Comment (niks3089) [reply src/commands/client/login.js:26]: I will work on this tomorrow as a separate PR. Merging this now
